version: '3.8'

services:
  broker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bazel-broker
    ports:
      - "8081:8081"
    environment:
      VAULT_ADDR: ${VAULT_ADDR:-http://vault:8200}
      VAULT_TOKEN: ${VAULT_ROOT_TOKEN}
      ISSUER: ${ISSUER:-http://localhost:8080}
      AUDIENCE: ${AUDIENCE:-vault-broker}
    networks:
      - ${DOCKER_NETWORK:-old_jenkins-vault-poc_default}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/.well-known/jwks.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    env_file:
      - .env

  # Vault setup service - runs once to configure existing Vault
  vault-setup:
    image: hashicorp/vault:1.16
    container_name: bazel-vault-setup
    environment:
      VAULT_ADDR: ${VAULT_ADDR:-http://vault:8200}
      VAULT_TOKEN: ${VAULT_ROOT_TOKEN}
    volumes:
      - ./vault/setup.sh:/setup.sh:ro
    networks:
      - ${DOCKER_NETWORK:-old_jenkins-vault-poc_default}
    depends_on:
      broker:
        condition: service_healthy
    command: |
      sh -c "
        echo 'Waiting for broker to be ready...'
        until curl -f http://broker:8081/.well-known/jwks.json; do sleep 2; done
        echo 'Setting up Vault configuration for Bazel JWT authentication...'
        /setup.sh
        echo 'Vault setup complete!'
      "
    restart: "no"
    env_file:
      - .env

# Use external network from existing Jenkins/Vault setup
networks:
  ${DOCKER_NETWORK:-old_jenkins-vault-poc_default}:
    external: true