services:
  broker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bazel-broker
    ports:
      - "8081:8081"
    environment:
      VAULT_ADDR: ${VAULT_ADDR:-http://vault:8200}
      VAULT_ROOT_TOKEN: ${VAULT_ROOT_TOKEN}
      OKTA_DOMAIN: ${OKTA_DOMAIN}
      OKTA_CLIENT_ID: ${OKTA_CLIENT_ID}
      OKTA_CLIENT_SECRET: ${OKTA_CLIENT_SECRET}
      OKTA_AUTH_SERVER_ID: ${OKTA_AUTH_SERVER_ID}
      OKTA_REDIRECT_URI: ${OKTA_REDIRECT_URI:-http://localhost:8081/auth/callback}
    networks:
      - jenkins-vault-poc_default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    env_file:
      - .env

# Use external network from existing Jenkins/Vault setup
networks:
  jenkins-vault-poc_default:
    external: true